services:
  mailserver:
    container_name: mailserver
    image: maildev/maildev
    ports:
      - '1025:1025'   # SMTP
      - '1080:1080'   # Web UI

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
      target: development
    # ホストマシンから直接アクセスできるように設定
    ports:
      - "3306:3306"
    # データベースの内容を永続化する
    volumes:
      - nestjs-starter-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password!
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Password!
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -pPassword!"
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  nestjs-starter-db:
