services:
  mailserver:
    container_name: mailserver
    image: maildev/maildev
    ports:
      - '1025:1025'   # SMTP
      - '1080:1080'   # Web UI

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
      target: development
    # ホストマシンから直接アクセスできるように設定
    ports:
      - "5432:5432"
    # データベースの内容を永続化する
    volumes:
      - nestjs-starter-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password!
      - POSTGRES_DB=sample
      - APP_USER_PASSWORD=Password!
    healthcheck:
      test: "pg_isready -U postgres -d sample"
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  nestjs-starter-db:
