# この処理は本来パイプラインで完結する。
# このスタータープロジェクトではデプロイ先のDBがないため、Dockerfileで方法を明示している
FROM node:22-alpine
# pnpmの設定
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Set the working directory inside the container
WORKDIR /app

# Copy the application files
COPY . .

# Install the application dependencies
RUN corepack enable && \
  pnpm i --frozen-lockfile && \
  pnpm run prisma:generate

# Command to run the application
CMD ["pnpm", "run", "prisma:deploy"]

