# Baseイメージ
FROM node:22-alpine
# pnpmの設定
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Set the working directory inside the container
WORKDIR /app

# Copy the application files
COPY . .

# Install the application dependencies
RUN corepack enable && \
  pnpm i --frozen-lockfile && \
  pnpm prisma:generate

# Command to run the application
CMD ["pnpm", "prisma:deploy"]

