allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': false
  esbuild: true
  prisma: true
  protobufjs: false

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - prisma
  - protobufjs
  - unrs-resolver

minimumReleaseAge: 1440
