name: API Pull Request Workflow

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "api/**"

defaults:
  run:
    working-directory: api

jobs:
  # APIのビルドとテストを検証
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Prismaコード生成
        run: pnpm run prisma:generate
        env:
          MIGRATION_DATABASE_URL: "postgresql://dummy"
      - name: ビルドチェック
        run: pnpm run build
      - name: テスト実行
        run: pnpm run test:cov

  # APIの静的解析とフォーマットチェック
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: 静的解析
        run: pnpm run lint
      - name: フォーマッタチェック
        run: pnpm run format:check
